import pandas as pd
import numpy as np


rng = np.random.default_rng(seed=42)
activities_raw = [
    {
        'id': 48,
        'name': 'Content Moderation',
        'activity_type': 'Moderation — Content',
        'work_type': 'Reactive',
        'frequency': 'Daily',
        'count_per_month': 1,
        'description': 'Мониторинг контента с фокусом на первых постах новичков и ответах опытных участников новичкам. Цель — сохранить атмосферу гостеприимства.',
        'target_segments': ['Lurker', 'Active Users', 'Core Users', 'Super Users'],
        'targets': ['Onboarding', 'Retention'],
        'key_metrics': [
            'Monthly Number Of Actions Per User',
            'Monthly Continue Participating After 1st Post',
            'Monthly Continue Participating After 2nd Post',
            'Monthly Continue Participating After 3rd Post',
            'Monthly Leave To Start',
            'Monthly Churn',
        ],
    },
    {
        'id': 49,
        'name': 'Flag Moderation',
        'activity_type': 'Moderation — Flag',
        'work_type': 'Reactive',
        'frequency': 'Daily',
        'count_per_month': 1,
        'description': 'Проверка и обработка контента отмеченного пользователями как нарушающего правила. По каждому флагу принимается решение: удалить, предупредить, переместить или отклонить.',
        'target_segments': ['Lurker', 'Active Users'],
        'targets': ['Retention'],
        'key_metrics': [
            'Monthly Number Of Actions Per User',
            'Monthly Percent Of Posts With Reply',
            'Monthly Continue Participating After 1st Post',
            'Monthly Continue Participating After 2nd Post',
            'Monthly Continue Participating After 3rd Post',
            'Monthly Leave To Start',
            'Monthly Churn',
        ],
    },
    {
        'id': 50,
        'name': 'Off-Topic Conversation Starter',
        'activity_type': 'Post — Off-Topic',
        'work_type': 'Proactive',
        'frequency': 'Weekly',
        'count_per_month': 1,
        'description': 'Создание тредов с off-topic разговорами. Пост включает личный опыт автора и открытый вопрос приглашающий других поделиться мнением.',
        'target_segments': ['Regular Users', 'Engaged Users', 'Core Users', 'Super Users'],
        'targets': ['Engagement', 'Retention'],
        'key_metrics': [
            'Monthly Number Of Actions Per User',
            'Monthly Number Of Discussions',
            'Monthly Churn',
        ],
    },
    {
        'id': 51,
        'name': 'Welcoming Newcomers',
        'activity_type': 'Post — Newcomers',
        'work_type': 'Proactive',
        'frequency': 'Weekly',
        'count_per_month': 1,
        'description': 'Регулярное приветствие новых участников ещё не написавших ни одного сообщения. Тегает новичков и приглашает представиться.',
        'target_segments': ['Lurker', 'Active Users'],
        'targets': ['Conversion', 'Onboarding'],
        'key_metrics': [
            'Monthly Active Users',
            'Monthly Start Acting',
        ],
    },
    {
        'id': 52,
        'name': 'Create Opportunities for Users to Participate',
        'activity_type': 'Post — Newcomers',
        'work_type': 'Proactive',
        'frequency': 'Weekly',
        'count_per_month': 1,
        'description': 'Создание дискуссионного треда с открытым вопросом по конкретной теме. Даёт участникам возможность поделиться экспертизой.',
        'target_segments': ['Regular Users', 'Engaged Users', 'Core Users', 'Super Users'],
        'targets': ['Engagement', 'Retention'],
        'key_metrics': [
            'Monthly Number Of Actions Per User',
            'Monthly Number Of Active Days Per User',
            'Monthly Contribution Frequency',
        ],
    },
    {
        'id': 53,
        'name': 'Answer Unanswered Questions',
        'activity_type': 'Post',
        'work_type': 'Proactive',
        'frequency': 'Daily',
        'count_per_month': 1,
        'description': 'Мониторинг вопросов без ответа и реакция на них в течение 20 часов. Особое внимание первым вопросам новичков.',
        'target_segments': ['Regular Users', 'Engaged Users', 'Core Users', 'Super Users'],
        'targets': ['Engagement', 'Retention'],
        'key_metrics': [
            'Monthly Number Of Actions Per User',
            'Monthly Number Of Active Days Per User',
            'Monthly Contribution Frequency',
        ],
    },
    {
        'id': 54,
        'name': 'User Interview',
        'activity_type': 'Post — User Interview',
        'work_type': 'Proactive',
        'frequency': 'Weekly',
        'count_per_month': 1,
        'description': 'Текстовое или видео интервью с участником сообщества. Раскрывает его сильные стороны, интересы и путь в сообществе.',
        'target_segments': ['Regular Users', 'Engaged Users', 'Core Users', 'Super Users'],
        'targets': ['Engagement', 'Retention'],
        'key_metrics': [
            'Monthly Number Of Actions Per User',
            'Monthly Number Of Active Days Per User',
            'Monthly Active Users',
            'Monthly Contribution Frequency',
        ],
    },
    {
        'id': 55,
        'name': 'Event Overview',
        'activity_type': 'Post — Event Overview',
        'work_type': 'Proactive',
        'frequency': 'Weekly',
        'count_per_month': 1,
        'description': 'Пост описывающий суть онлайн или офлайн мероприятия. Фиксирует ключевые моменты и даёт тем кто не присутствовал понимание что произошло.',
        'target_segments': ['Regular Users', 'Engaged Users', 'Core Users', 'Super Users'],
        'targets': ['Engagement', 'Retention'],
        'key_metrics': [
            'Monthly Number Of Actions Per User',
            'Monthly Number Of Active Days Per User',
            'Monthly Active Users',
            'Monthly Contribution Frequency',
        ],
    },
    {
        'id': 56,
        'name': 'Congratulatory Post',
        'activity_type': 'Post — Congratulatory Post',
        'work_type': 'Reactive',
        'frequency': 'Weekly',
        'count_per_month': 1,
        'description': 'Пост отмечающий значимое достижение участника. Цель — поделиться хорошей новостью и создать позитивный момент для сообщества.',
        'target_segments': ['Regular Users', 'Engaged Users', 'Core Users', 'Super Users'],
        'targets': ['Engagement', 'Retention'],
        'key_metrics': [
            'Monthly Number Of Actions Per User',
            'Monthly Number Of Active Days Per User',
            'Monthly Active Users',
            'Monthly Contribution Frequency',
        ],
    },
    {
        'id': 57,
        'name': "User's Success Story",
        'activity_type': 'Post — Success Story',
        'work_type': 'Reactive',
        'frequency': 'Weekly',
        'count_per_month': 1,
        'description': 'Пост рассказывающий историю участника достигшего чего-то значимого с помощью сообщества. Вдохновляет других и показывает ценность участия.',
        'target_segments': ['Regular Users', 'Engaged Users', 'Core Users', 'Super Users'],
        'targets': ['Engagement', 'Retention'],
        'key_metrics': [
            'Monthly Number Of Actions Per User',
            'Monthly Number Of Active Days Per User',
            'Monthly Active Users',
            'Monthly Contribution Frequency',
        ],
    },
    {
        'id': 58,
        'name': 'Community Digest',
        'activity_type': 'Post — Digest',
        'work_type': 'Proactive',
        'frequency': 'Weekly',
        'count_per_month': 1,
        'description': 'Регулярный пост выделяющий что происходило в сообществе за период. Держит участников в курсе и признаёт вклад активных членов.',
        'target_segments': ['Regular Users', 'Engaged Users', 'Core Users', 'Super Users'],
        'targets': ['Engagement', 'Retention'],
        'key_metrics': [
            'Monthly Churn',
            'Monthly Active Users',
            'Monthly Contribution Frequency',
            'Monthly Total Number Of Actions',
            'Monthly Number Of Active Days Per User',
        ],
    },
    {
        'id': 59,
        'name': 'Announcement',
        'activity_type': 'Post — Announcement',
        'work_type': 'Proactive',
        'frequency': 'Weekly',
        'count_per_month': 1,
        'description': 'Пост для публикации новостей и обновлений. Используется для любых анонсов не покрытых другими шаблонами.',
        'target_segments': ['Regular Users', 'Engaged Users', 'Core Users', 'Super Users'],
        'targets': ['Engagement', 'Retention'],
        'key_metrics': [
            'Monthly Churn',
            'Monthly Active Users',
        ],
    },
    {
        'id': 60,
        'name': 'Feature Announcement',
        'activity_type': 'Post — Feature Post',
        'work_type': 'Proactive',
        'frequency': 'Weekly',
        'count_per_month': 1,
        'description': 'Пост анонсирующий новую функцию или обновление продукта. Объясняет какую проблему решает компания и собирает обратную связь.',
        'target_segments': ['Regular Users', 'Engaged Users', 'Core Users', 'Super Users'],
        'targets': ['Engagement', 'Retention'],
        'key_metrics': [
            'Monthly Churn',
            'Monthly Active Users',
        ],
    },
    {
        'id': 61,
        'name': 'Self-Disclosure Post',
        'activity_type': 'Post — Self Disclosure',
        'work_type': 'Proactive',
        'frequency': 'Weekly',
        'count_per_month': 1,
        'description': 'Пост побуждающий участников делиться личными историями и опытом. Цель — углубить связи между участниками и выстроить доверие.',
        'target_segments': ['Regular Users', 'Engaged Users', 'Core Users', 'Super Users'],
        'targets': ['Engagement', 'Retention'],
        'key_metrics': [
            'Monthly Churn',
            'Monthly Contribution Frequency',
            'Monthly Leave To Start',
            'Monthly Active Users',
        ],
    },
    {
        'id': 62,
        'name': 'Contest Announcement',
        'activity_type': 'Post — Contest Post',
        'work_type': 'Proactive',
        'frequency': 'Once',
        'count_per_month': 1,
        'description': 'Пост анонсирующий конкурс или челлендж. Запускает мероприятие и объясняет правила, сроки, критерии оценки и призы.',
        'target_segments': ['Regular Users', 'Engaged Users', 'Core Users', 'Super Users'],
        'targets': ['Engagement', 'Retention', 'Conversion'],
        'key_metrics': [
            'Monthly Churn',
            'Monthly Contribution Frequency',
            'Monthly Leave To Start',
            'Monthly Start Acting',
            'Monthly Active Users',
        ],
    },
    {
        'id': 63,
        'name': 'Community Report',
        'activity_type': 'Post — Report Post',
        'work_type': 'Proactive',
        'frequency': 'Once',
        'count_per_month': 1,
        'description': 'Пост подводящий итоги работы сообщества за период. Включает метрики роста, highlights активности и ретроспективный анализ.',
        'target_segments': ['Regular Users', 'Engaged Users', 'Core Users', 'Super Users'],
        'targets': ['Retention'],
        'key_metrics': [
            'Monthly Churn',
        ],
    },
    {
        'id': 64,
        'name': 'Social Initiative Announcement',
        'activity_type': 'Post — Social Initiative',
        'work_type': 'Proactive',
        'frequency': 'Once',
        'count_per_month': 1,
        'description': 'Пост с предложением решить проблему важную для сообщества или общества в целом. Наградой является совместный результат.',
        'target_segments': ['Regular Users', 'Engaged Users', 'Core Users', 'Super Users'],
        'targets': ['Retention'],
        'key_metrics': [
            'Monthly Number Of Actions Per User',
            'Monthly Number Of Active Days Per User',
            'Monthly Contribution Frequency',
        ],
    },
    {
        'id': 65,
        'name': 'Content Seeding',
        'activity_type': 'Post — Social Initiative',
        'work_type': 'Proactive',
        'frequency': 'Weekly',
        'count_per_month': 1,
        'description': 'Пост с предложением решить проблему важную для сообщества. В отличие от конкурса нет приза — наградой является совместный результат.',
        'target_segments': ['Regular Users', 'Engaged Users', 'Core Users', 'Super Users'],
        'targets': ['Retention'],
        'key_metrics': [
            'Monthly Number Of Actions Per User',
            'Monthly Number Of Active Days Per User',
            'Monthly Contribution Frequency',
        ],
    },
    {
        'id': 66,
        'name': "Setting Up a Place for Users' Introductions",
        'activity_type': 'Community Setup — Introduce Yourself Thread',
        'work_type': 'Proactive',
        'frequency': 'Once',
        'count_per_month': 1,
        'description': 'Создание канала или треда где новые участники могут рассказать о себе и получить первый положительный опыт участия.',
        'target_segments': ['Lurker', 'Active Users'],
        'targets': ['Conversion', 'Onboarding'],
        'key_metrics': [
            'Monthly Active Users',
            'Monthly Start Acting',
        ],
    },
    {
        'id': 67,
        'name': 'Creating Code of Conduct',
        'activity_type': 'Community Setup — Creating Code of Conduct',
        'work_type': 'Proactive',
        'frequency': 'Once',
        'count_per_month': 1,
        'description': 'Пост устанавливающий правила поведения в сообществе. Задаёт чёткие ожидания и даёт модераторам основу для действий.',
        'target_segments': ['Active Users', 'Regular Users', 'Engaged Users', 'Core Users', 'Super Users'],
        'targets': ['Retention'],
        'key_metrics': [
            'Monthly Churn',
            'Monthly Leave To Start',
            'Monthly Active Users',
            'Monthly Utilization',
        ],
    },
    {
        'id': 68,
        'name': 'Creating FAQ Page or Post',
        'activity_type': 'Community Setup — Creating Code of Conduct',
        'work_type': 'Proactive',
        'frequency': 'Weekly',
        'count_per_month': 1,
        'description': 'Структурированная коллекция часто задаваемых вопросов. Помогает новичкам быстро найти информацию и снижает количество повторяющихся вопросов.',
        'target_segments': ['Lurker', 'Active Users'],
        'targets': ['Conversion'],
        'key_metrics': [
            'Monthly Start Acting',
            'Monthly Active Users',
        ],
    },
    {
        'id': 69,
        'name': 'Creative Content Contest',
        'activity_type': 'Event — Creative Content',
        'work_type': 'Proactive',
        'frequency': 'Once',
        'count_per_month': 1,
        'description': 'Конкурс где участники создают оригинальный контент на заданную тему. Цель — стимулировать творчество, повысить вовлечённость и создать интересный контент.',
        'target_segments': ['Lurker', 'Active Users'],
        'targets': ['Conversion'],
        'key_metrics': [
            'Monthly Contribution Frequency',
        ],
    },
    {
        'id': 70,
        'name': 'Prize Giveaway',
        'activity_type': 'Post — Prize Giveaway',
        'work_type': 'Proactive',
        'frequency': 'Once',
        'count_per_month': 1,
        'description': 'Конкурс где участники соревнуются за приз. Победители выбираются случайно или по критериям. Цель — повысить видимость и привлечь новых участников.',
        'target_segments': ['Lurker', 'Active Users'],
        'targets': ['Conversion', 'Retention', 'Engagement'],
        'key_metrics': [
            'Monthly Churn',
            'Monthly Start Acting',
            'Monthly Active Users',
        ],
    },
    {
        'id': 71,
        'name': 'AMA Session',
        'activity_type': 'Event — AMA Session',
        'work_type': 'Proactive',
        'frequency': 'Once',
        'count_per_month': 1,
        'description': 'Живая сессия вопросов и ответов с гостем — разработчиком, основателем, экспертом. Цель — выстроить доверие и создать прямую связь между сообществом и ключевыми людьми.',
        'target_segments': ['Lurker', 'Active Users'],
        'targets': ['Conversion', 'Retention', 'Engagement'],
        'key_metrics': [
            'Monthly Churn',
            'Monthly Start Acting',
            'Monthly Active Users',
        ],
    },
    {
        'id': 72,
        'name': 'Game Night',
        'activity_type': 'Event — Game Night',
        'work_type': 'Proactive',
        'frequency': 'Weekly',
        'count_per_month': 1,
        'description': 'Регулярное живое мероприятие где участники играют вместе и взаимодействуют в реальном времени. Сочетает совместную активность с социальным сближением.',
        'target_segments': ['Lurker', 'Active Users'],
        'targets': ['Conversion', 'Retention', 'Engagement'],
        'key_metrics': [
            'Monthly Active Users',
            'Monthly Churn',
        ],
    },
    {
        'id': 73,
        'name': 'Offline Meetup',
        'activity_type': 'Event — Offline Meetup',
        'work_type': 'Proactive',
        'frequency': 'Weekly',
        'count_per_month': 1,
        'description': 'Живая встреча участников сообщества в неформальной обстановке. Укрепляет связи сильнее чем онлайн-взаимодействие. Может быть организована компанией или участниками.',
        'target_segments': ['Lurker', 'Active Users'],
        'targets': ['Conversion', 'Onboarding'],
        'key_metrics': [
            'Monthly Churn',
            'Monthly Contribution Frequency',
        ],
    },
    {
        'id': 74,
        'name': 'Personal Invitations',
        'activity_type': 'External — Personal Invitation',
        'work_type': 'Proactive',
        'frequency': 'Weekly',
        'count_per_month': 1,
        'description': 'Отправка прямых персональных сообщений потенциальным участникам которые получат пользу от вступления в сообщество.',
        'target_segments': ['Lurker', 'Active Users'],
        'targets': ['Conversion'],
        'key_metrics': [
            'Monthly Start Acting',
            'Monthly Active Users',
        ],
    },
    {
        'id': 75,
        'name': 'Community Chat Presence',
        'activity_type': 'Event — Chat Presence',
        'work_type': 'Proactive',
        'frequency': 'Weekly',
        'count_per_month': 1,
        'description': 'Регулярное неформальное присутствие сотрудника компании в чате сообщества. Цель — выстроить личный контакт, создать канал для обратной связи и очеловечить бренд.',
        'target_segments': ['Engaged Users', 'Core Users', 'Super Users'],
        'targets': ['Engagement', 'Retention'],
        'key_metrics': [
            'Monthly Number Of Actions Per User',
            'Monthly Percent Of Posts With Reply',
            'Monthly Contribution Frequency',
            'Monthly Churn',
        ],
    },
]

df_activities = pd.DataFrame(activities_raw).set_index('id').sort_index()
df_activities['hours_per_activity'] = rng.choice(
    [0.5, 1.0, 1.5, 2.0],
    size=len(df_activities),
)

print(df_activities)

PREDICTOR_ACTIVITY_MAP = {

    'new_user_activation_rate_7d': {
        'community_type': 'both',
        'direction': 'increase',
        'activities': [
            {'id': 51, 'rationale': 'Прямое приветствие новичков по имени снижает барьер первого ответа и создаёт социальное обязательство вернуться'},
            {'id': 66, 'rationale': 'Тред для знакомств даёт новичку безопасный первый пост с гарантированным откликом — первое позитивное действие повышает шанс второго'},
            {'id': 68, 'rationale': 'FAQ снижает трение при старте: новичок находит ответ сам и не уходит с ощущением растерянности до истечения 7 дней'},
            {'id': 48, 'rationale': 'Модерация первых постов новичков защищает их от негативных реакций, которые чаще всего убивают желание вернуться'},
            {'id': 52, 'rationale': 'Открытый вопрос по теме сообщества даёт новичку повод ответить без необходимости самому формулировать тему'},
        ],
    },

    'newcomer_no_response_rate_1h': {
        'community_type': 'both',
        'direction': 'decrease',
        'activities': [
            {'id': 53, 'rationale': 'Активность прямо описывает мониторинг вопросов без ответа с целевым временем реакции 20 часов'},
            {'id': 48, 'rationale': 'Контент-модерация с фокусом на первых постах новичков обеспечивает быстрый квалифицированный ответ от опытных участников'},
            {'id': 75, 'rationale': 'Постоянное присутствие сотрудника компании в чате даёт живой источник быстрых ответов в первый час'},
        ],
    },

    'reactivated_rate': {
        'community_type': 'both',
        'direction': 'increase',
        'activities': [
            {'id': 58, 'rationale': 'Дайджест напоминает неактивным участникам что они пропустили — классический триггер возврата через FOMO'},
            {'id': 71, 'rationale': 'AMA с заметным гостем создаёт событие достаточной ценности чтобы вернуть участников после паузы'},
            {'id': 70, 'rationale': 'Розыгрыш приза — краткосрочный, но эффективный стимул для возврата ранее активных участников'},
            {'id': 63, 'rationale': 'Отчёт сообщества показывает рост и достижения — реактивирует тех кто уходил в период стагнации'},
            {'id': 74, 'rationale': 'Персональное приглашение — самый прямой способ вернуть конкретного участника'},
        ],
    },

    'average_thread_messages': {
        'community_type': 'both',
        'direction': 'increase',
        'activities': [
            {'id': 50, 'rationale': 'Off-topic треды намеренно создаются как дискуссии без правильного ответа — это максимизирует число сообщений в треде'},
            {'id': 52, 'rationale': 'Открытый вопрос по теме экспертизы провоцирует развёрнутые ответы и дискуссии между участниками'},
            {'id': 61, 'rationale': 'Self-disclosure пост создаёт эмоциональный резонанс — участники делятся своим опытом, тред разрастается органически'},
            {'id': 75, 'rationale': 'Активное присутствие сотрудника компании поддерживает разговор вопросами и реакциями, не давая треду заглохнуть'},
            {'id': 64, 'rationale': 'Социальная инициатива требует координации участников — это структурно генерирует много сообщений в треде'},
        ],
    },

    'average_replies_per_discussion': {
        'community_type': 'chat',
        'direction': 'increase',
        'activities': [
            {'id': 50, 'rationale': 'Off-topic треды создают низкобарьерный контекст для ответов — среднее число реплаев выше чем в технических обсуждениях'},
            {'id': 71, 'rationale': 'AMA по формату генерирует максимум реплаев: один вопрос гостю собирает десятки ответов и follow-up вопросов'},
            {'id': 52, 'rationale': 'Дискуссионный тред с открытым вопросом провоцирует цепочку реплаев между несколькими участниками'},
            {'id': 75, 'rationale': 'Присутствие сотрудника компании в чате создаёт точку притяжения для обсуждений'},
        ],
    },

    'percentage_new_users_receiving_first_reply': {
        'community_type': 'qa',
        'direction': 'increase',
        'activities': [
            {'id': 53, 'rationale': 'Активность прямо нацелена на первые вопросы новичков — мониторинг и ответ в течение 20 часов напрямую двигает эту метрику'},
            {'id': 48, 'rationale': 'Контент-модерация следит за тем чтобы опытные участники отвечали новичкам — создаёт культуру отклика'},
            {'id': 51, 'rationale': 'Приветствие новичков увеличивает их видимость и повышает вероятность что их первый вопрос не останется без ответа'},
        ],
    },

    'unanswered_rate': {
        'community_type': 'qa',
        'direction': 'decrease',
        'activities': [
            {'id': 53, 'rationale': 'Прямая активность по мониторингу вопросов без ответа — самый очевидный способ снизить unanswered_rate'},
            {'id': 52, 'rationale': 'Создание возможностей для участия вовлекает опытных пользователей в регулярный мониторинг новых вопросов'},
            {'id': 48, 'rationale': 'Контент-модерация с фокусом на ответах опытных участников системно снижает долю вопросов без реакции'},
        ],
    },

    'resolution_rate': {
        'community_type': 'qa',
        'direction': 'increase',
        'activities': [
            {'id': 53, 'rationale': 'Ответ на вопрос в течение 20 часов увеличивает шанс что автор вернётся и отметит ответ принятым'},
            {'id': 68, 'rationale': 'FAQ снижает число вопросов на которые сложно дать закрытый ответ — остаются вопросы где принятый ответ реалистичен'},
            {'id': 48, 'rationale': 'Модерация качества ответов повышает вероятность что автор вопроса сочтёт ответ достаточным для закрытия'},
        ],
    },

    'median_time_to_be_answered_hours': {
        'community_type': 'qa',
        'direction': 'decrease',
        'activities': [
            {'id': 53, 'rationale': 'Мониторинг с временным ориентиром 20 часов прямо воздействует на медианное время до принятого ответа'},
            {'id': 48, 'rationale': 'Активная модерация ответов ускоряет цикл вопрос→ответ→принятие за счёт фокуса на качестве первых реакций'},
            {'id': 52, 'rationale': 'Регулярное вовлечение экспертов через дискуссии поддерживает их активность — они быстрее отвечают на новые вопросы'},
        ],
    },
}

_records = []
for predictor, entry in PREDICTOR_ACTIVITY_MAP.items():
    for act in entry['activities']:
        _records.append({
            'predictor':      predictor,
            'community_type': entry['community_type'],
            'direction':      entry['direction'],
            'activity_id':    act['id'],
            'rationale':      act['rationale'],
        })

df_predictor_activity = pd.DataFrame(_records)
print(df_predictor_activity)

stage_to_segments = {
        'growth':     {'Lurker', 'Active Users'},
        'stagnation': {'Regular Users', 'Engaged Users'},
        'decline':    {'Core Users', 'Super Users', 'Engaged Users'},
    }